apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  labels:
    app: registry-app
spec:
  selector:
    app: registry-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
